# Generated by Django 4.1 on 2023-05-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Words",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_word", models.CharField(max_length=100, verbose_name="en_word")),
                (
                    "ru_translation",
                    models.CharField(max_length=100, verbose_name="ru_translation"),
                ),
            ],
        ),
    ]
